start  : blocks

blocks : block+

block :  header topics _BREAK_LINE*

header : "[" NAME ": " NAME "]" _BREAK_LINE
       | "[" NAME "]" _BREAK_LINE -> header_story


topics : topic+

topic : MARKER _SPACE (element _SPACE*)+ _BREAK_LINE

intent : "{" NAME "}{" NAME "}"

synonym : "{" NAME "}{" NAME ":" (TEXT "|"?)+ "}"

element: text 
	  | synonym
		| intent

text : TEXT

MARKER : /[>-]/
TEXT : /[\w\[\]\-+_?!:;,. #]+/
NAME: /[\w\d\-_]+/
_BREAK_LINE : /\n/
_SPACE: " "
